export const GET_AUTO_COMPLETE_WEATHER = 'GET_AUTO_COMPLETE_WEATHER';
export const GET_FIVE_DAYS_WEATHER = 'GET_FIVE_DAYS_WEATHER';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const CLEAN_AUTO_COMPLETE = 'CLEAN_AUTO_COMPLETE';
export const WEATHER_ERROR = 'WEATHER_ERROR';

export const SET_LOADING = 'SET_LOADING';

export const GET_FAVORITES = 'GET_FAVORITES';
export const IS_FAVORITE = 'IS_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const FAVORITES_ERROR = 'FAVORITES_ERROR';


